# Generated by Django 2.2.7 on 2019-11-28 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancionId', models.IntegerField()),
                ('cancion', models.CharField(max_length=200)),
                ('artista', models.TextField(max_length=100)),
                ('duracion', models.CharField(max_length=5)),
                ('pais', models.IntegerField(choices=[(1, 'Chile'), (2, 'Argentina'), (3, 'Perú'), (4, 'Paraguay'), (4, 'Brasil'), (5, 'Ecuador'), (6, 'Colombia'), (7, 'Paraguay'), (8, 'Otro')], default=1, max_length=2)),
                ('registro_fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
