# Generated by Django 2.2.7 on 2019-11-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='pais',
            field=models.IntegerField(choices=[(1, 'Chile'), (2, 'Argentina'), (3, 'Perú'), (4, 'Paraguay'), (4, 'Brasil'), (5, 'Ecuador'), (6, 'Colombia'), (7, 'Paraguay'), (8, 'Otro')], default=1),
        ),
    ]
