# Generated by Django 2.2.7 on 2019-11-28 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audiodog', '0002_auto_20191128_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('email', models.TextField(max_length=100)),
                ('nacimiento_fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefonos', models.CharField(max_length=100)),
                ('region', models.IntegerField(choices=[(1, 'Arica y Parinacota'), (2, 'Tarapacá'), (3, 'Antofagasta'), (4, 'Atacama'), (5, 'Coquimbo'), (6, 'Valparaíso'), (7, 'Metropolitana'), (8, 'OHiggins'), (9, 'Maule'), (10, 'Ñuble'), (11, 'Biobio'), (12, 'Araucanía'), (13, 'Los Rïos'), (14, 'Los Lagos'), (15, 'Aisén'), (16, 'Magallanes')], default=6)),
                ('registro_fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
