# Generated by Django 2.2.7 on 2019-11-28 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audiodog', '0004_auto_20191128_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cancion',
            new_name='Canciones',
        ),
        migrations.RenameModel(
            old_name='Ciudad',
            new_name='Ciudades',
        ),
        migrations.RenameModel(
            old_name='Pais',
            new_name='Paises',
        ),
        migrations.RenameModel(
            old_name='Region',
            new_name='Regiones',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
