# Generated by Django 2.2.7 on 2019-11-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0006_auto_20191128_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='ciudadId',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='regionId',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='cancionId',
        ),
    ]
