# Generated by Django 2.2.7 on 2019-11-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0007_auto_20191128_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='paisId',
        ),
        migrations.RemoveField(
            model_name='region',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
