# Generated by Django 2.2.7 on 2019-11-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0008_auto_20191128_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='imagen',
            field=models.FileField(default='', upload_to='media/covers'),
        ),
    ]
