# Generated by Django 2.2.7 on 2019-11-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0009_cancion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(upload_to='media/cover/'),
        ),
    ]
