# Generated by Django 2.2.7 on 2019-11-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0012_auto_20191129_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(default='', upload_to='proyectos', verbose_name='Imagen'),
        ),
    ]
