# Generated by Django 2.2.7 on 2019-11-29 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0013_auto_20191129_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='region',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='audiodog.Ciudad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dispositivo',
            field=models.IntegerField(choices=[(1, 'Computador'), (2, 'Teléfono móvil'), (3, 'Tablet'), (4, 'Smart TV')], default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(default='', upload_to='cover', verbose_name='Imagen'),
        ),
    ]
