# Generated by Django 2.2.7 on 2019-11-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0015_auto_20191129_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dispositivo',
            field=models.TextField(max_length=100),
        ),
    ]
