# Generated by Django 2.2.7 on 2019-11-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0016_auto_20191129_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='archivo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
