# Generated by Django 2.2.7 on 2019-12-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0017_cancion_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='archivo',
            field=models.FileField(default='', upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='cancion',
            field=models.TextField(max_length=200),
        ),
    ]
