# Generated by Django 2.2.7 on 2019-12-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0018_auto_20191202_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alias',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='duracion',
            field=models.TextField(max_length=5),
        ),
    ]
