# Generated by Django 2.2.7 on 2019-12-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodog', '0019_auto_20191205_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='', max_length=100),
        ),
    ]
